name: surge app Deployment

on: [push]
jobs:
        build:
          name: jobs_Deploy_surge
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - name: install Node
              uses: actions/setup-node@v2-beta
              with:
                node-version: '12'
            - name: Setup Surge
              run: npm install --global surge
            - name: Execute Deployment with Surge
              run: surge ./ expense_tracker.surge.sh --token ${{ secrets.SURGE_SECRET}}


